### ISSUE TITLE
Must close and reopen window when changing server

### ISSUE THREAD

**Issue by ubellavance** [ppalucha/ksar2#15] opened 2018-05-17 19:07 UTC
I haven't used it a lot, but it looks like if you have one window open, create graphs, then realize that you wanted graphs for another server, it's better to close the window and, open a new one because otherwise the results are unexpected.

**Comment by ppalucha** [comment] 2018-08-14 20:38
It's not a bug, it's a feature ;-)
The expected behavior is to append the file to the currently loaded data (and not to replace current file). It allows you to load multiple files, e.g. from consecutive days. 
I'm closing the issue.

**Closed by ppalucha** 2018-08-14 20:38 UTC
